development:
  adapter: postgresql
  encoding: unicode
  database: legreedy_development
  pool: 5
  #username: postgres
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: legreedy_test
  pool: 5
  #username: postgres
  #password:
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: legreedy_production
  pool: 5
  # username: postgres
  # password:
  host: localhost
